POST https://backend-equipo4.onrender.com/create-order2
Content-Type: application/json

{
    "intent": "CAPTURE",
    "purchase_units": [
        {
            "amount": {
                "currency_code": "USD",
                "value": "105.70"
            }
        }
    ],
    "application_context": {
        "brand_name": "PLURALCURSOS.com",
        "landing_page": "NO_PREFERENCE",
        "user_action": "PAY_NOW",
        "return_url": "https://frontend-equipo4.onrender.com/capture-order",
        "cancel_url": "https://frontend-equipo4.onrender.com/cancel-payment"
    }
}
### order original
POST https://backend-equipo4.onrender.com/create-order
Content-Type: application/x-www-form-urlencoded
{
    "intent": "CAPTURE",
    "purchase_units": [
        {
            "amount": {
                "currency_code": "USD",
                "value": "150"
            }
        }
    ],
    "application_context": {
        "brand_name": "PLURALCURSOS.com",
        "landing_page": "NO_PREFERENCE",
        "user_action": "PAY_NOW",
        "return_url": "https://frontend-equipo4.onrender.com/capture-order",
        "cancel_url": "https://frontend-equipo4.onrender.com/cancel-payment"
    }
}